bootstrap: localimage
from: base.simg


%post
  apt-get update
  apt-get install -y  python3-tk \
                      python-pygraphviz
                      
  pip3 install --upgrade pip
  pip3 install  networkx \
                scipy \
                h5py \
                matplotlib \
                numpy \
                pandas \
                pygraphviz \
                pydot \
                pyyaml
